export const BUILD_EXAM_QUESTION = 'BUILD_EXAM_QUESTION'
export const RESET_EXAM_CREATION = 'RESET_EXAM_CREATION'

export const EXAM_SET_STATE = 'EXAM_SET_STATE'
export const EXAM_NEXT_QUESTION = 'EXAM_NEXT_QUESTION'
export const FINISH_EXAM = 'FINISH_EXAM'
export const EXAM_RETRY = 'EXAM_RETRY'

export const FETCH_EXAMS_START = 'FETCH_EXAMS_START'
export const FETCH_EXAMS_SUCCESS = 'FETCH_EXAMS_SUCCESS'
export const FETCH_EXAMS_ERROR = 'FETCH_EXAMS_ERROR'
export const FETCH_EXAM_SUCCESS = 'FETCH_EXAM_SUCCESS'


